### ISSUE TITLE
Add Sponsor logos to the footer

### ISSUE THREAD

**Issue by robbiethegeek** [AlxCodeCoffee/alxcodecoffee.github.io#2]
1. Phase2
   - URL
     - http://phase2technology.com/
   - Logo
     - https://www.phase2technology.com/wp-content/uploads/2015/06/logo-retina.png
2. The Motley Fool
   - URL
     - http://fool.com/
   - Logo
     - http://g.foolcdn.com/art/fool15/bg/fool-logo.png

**Comment by caseywatts** [comment]
done! :)
